import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    // Module 1
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      collapsed: false,
      items: [
        { type: 'doc', id: 'module-1-ros2-fundamentals/index' },
        { type: 'doc', id: 'module-1-ros2-fundamentals/setup-guide' },

        {
          type: 'category',
          label: 'Chapter 1: ROS 2 Fundamentals',
          collapsed: true,
          items: [
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-1/index' },
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-1/introduction-to-ros2' },
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-1/nodes-and-processes' },
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-1/topics-and-message-passing' },
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-1/services-and-parameters' },
          ],
        },

        {
          type: 'category',
          label: 'Chapter 2: Advanced Communication Patterns',
          collapsed: true,
          items: [
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-2/index' },
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-2/actions-for-complex-tasks' },
          ],
        },

        {
          type: 'category',
          label: 'Chapter 3: Robot Description and Modeling',
          collapsed: true,
          items: [
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-3/index' },
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-3/urdf-fundamentals' },
          ],
        },

        {
          type: 'category',
          label: 'Chapter 4: Integration with Simulation',
          collapsed: true,
          items: [
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-4/index' },
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-4/ros2-gazebo-integration' },
          ],
        },

        {
          type: 'category',
          label: 'Chapter 5: Applied Robotics Projects',
          collapsed: true,
          items: [
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-5/index' },
            { type: 'doc', id: 'module-1-ros2-fundamentals/chapter-5/designing-complete-applications' },
          ],
        },
      ],
    },

    // Module 2
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2-digital-twin',
        },
      ],
    },

    // Module 3
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-ai-robot-brain',
        },
      ],
    },
  ],
};

export default sidebars;