"""
Model for representing the numerical vector representation of a text chunk.
"""
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional


@dataclass
class EmbeddingVector:
    """
    Represents the numerical vector representation of a text chunk, generated by the Cohere model,
    with associated metadata and reference to the source chunk.
    """
    id: str
    text_chunk_id: str
    vector: List[float]
    model_name: str
    model_version: str
    embedding_size: int
    created_at: Optional[datetime] = None
    
    def __post_init__(self):
        """Validate the EmbeddingVector instance after initialization."""
        if not self.text_chunk_id:
            raise ValueError("text_chunk_id is required")
        
        if not self.vector:
            raise ValueError("vector is required")
        
        if not self.model_name:
            raise ValueError("model_name is required")
        
        if self.embedding_size != len(self.vector):
            raise ValueError("embedding_size must match the actual vector length")
        
        if self.created_at is None:
            self.created_at = datetime.now()